version: '3'

services:
  wolproxypyapi:
    image: wolproxypyapi:latest
    build: .
    container_name: wolproxypyapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    user: "${UID}:${GID}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
