# Project information
site_name: wolproxypyapi
site_url: https://github.com/bateman/wolproxypyapi
site_description: A FastAPI RESTful web service for routing Wake-On-LAN packets via Internet.
site_author: Fabio Calefato <fabio.calefato@uniba.it>

# Repository
repo_url: https://github.com/bateman/wolproxypyapi
repo_name: bateman/wolproxypyapi
edit_uri: "" #disables edit button

# Copyright
copyright: MIT License 2021-2024, Fabio Calefato

# Configuration
theme:
  name: readthedocs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [wolproxypyapi]

nav:
  - Home: index.md
  - About: about.md
  - Docstrings:
    - Api module: api.md
